### ISSUE TITLE
Project Alive?

### ISSUE THREAD

**Issue by digitalw** [RiccardoDeMasellis/FLLOAT#10]
Hi, Is this Project still alive?

**Comment by RiccardoDeMasellis** [comment]
We believe it works by doing what is written in the description. So we are not actively working on it, if this is what you mean.

**Comment by digitalw** [comment]
I was wondering about the performance improvements worked on in the optimizations branch :-)

**Comment by RiccardoDeMasellis** [comment]
I am not working on it, as in general the optimization I had in mind does not work. 

However, for input formulas with a specific "structure", it is possible to speed up the process of automata generation. In particular if you have a boolean combination of temporal formulas, instead of building the automaton for the whole formula, you can build the automata for the temporal (sub-)formulas, minimize them and then combine the resulting automata together using the well-known operations on automata.

**Comment by digitalw** [comment]
Thanks for the hint. I will give it a try.

**Comment by RiccardoDeMasellis** [comment]
The general problem is that the procedure does not generate minimal automata, which kills the performances. So, if you can (but that depends on your input formulas) is better to: (i) push inside the temporal operators; (ii) use the automaton construction procedure in the temporal sub-formulas; (iii) minimize the resulting automata and finally (iv) re-combine them with the automata operations (intersection for and, union for or and negation for not).
